#!/usr/bin/env bash
# Find our location
SELF_LOCATION=$(cd "$(dirname "$0")" ; pwd)

# Was this invoked as a link ?
if [ -L "$0" ]
then
	LINKTO=$(/usr/bin/readlink "$0")

	# Is the link a relative path
	if [[ "${LINKTO}" = /* ]]
	then
	    # absolute path so just invoke it
		exec "${LINKTO}" "$@"
	else
	    # invoke by prepending our folder
		exec "${SELF_LOCATION}/${LINKTO}" "$@"
	fi
fi

function abspath() {
	if [[ "$1" = /* ]]
	then
	    echo "$1"
	else
	    local file="$(pwd)/$1"
	    file="$(cd "$(dirname "${file}")";pwd)/$(basename "${file}")"
		echo "${file}"
	fi
}

# TODO Loop through and convert "$@" into array of absolute file paths

# Run IDE
"${SELF_LOCATION}/AptanaRadRails.app/Contents/MacOS/AptanaRadRails" -application com.aptana.commandline.launcher.LauncherApplication "$(abspath "$@")" > /dev/null 2>&1 &

# Detach it
disown -h %-
disown %-