#!/usr/bin/env bash
# Find our location
SELF_LOCATION=$(cd "$(dirname "$0")" ; pwd)

# Was this invoked as a link ?
if [ -L "$0" ]
then
	LINKTO=$(/usr/bin/readlink "$0")

	# Is the link a relative path
	if [[ "${LINKTO}" = /* ]]
	then
	    # absolute path so just invoke it
		exec "${LINKTO}" "$@"
	else
	    # invoke by prepending our folder
		exec "${SELF_LOCATION}/${LINKTO}" "$@"
	fi
fi

function abspath() {
	if [[ "$1" = /* ]]
	then
	    echo "$1"
	else
	    local file="$(pwd)/$1"
	    file="$(cd "$(dirname "${file}")";pwd)/$(basename "${file}")"
		echo "${file}"
	fi
}

# Loop through and convert "$@" into array of absolute file paths
FILE_INDEX=0
for FILE_PATH in "$@"
do
	ABSOLUTE_FILE_PATHS[${FILE_INDEX}]="$(abspath "${FILE_PATH}")"
	((FILE_INDEX++))
done

# Run IDE
"${SELF_LOCATION}/AptanaStudio3.app/Contents/MacOS/AptanaStudio3" -application com.aptana.commandline.launcher.LauncherApplication "${ABSOLUTE_FILE_PATHS[@]}" > /dev/null 2>&1 &

# Detach it
disown -h %-
disown %-