#!/usr/bin/env bash
# Find our location
SELF_LOCATION=$(cd "$(dirname "$0")" ; pwd)

# Was this invoked as a link ?
if [ -L "$0" ]
then
	if [ -x /bin/readlink ]
	then
		LINKTO=$(/bin/readlink "$0")
	else
		LINKTO=$(/usr/bin/readlink "$0")
	fi

	# Is the link a relative path
	if [[ "${LINKTO}" = /* ]]
	then
	    # absolute path so just invoke it
		exec "${LINKTO}" "$@"
	else
	    # invoke by prepending our folder
		exec "${SELF_LOCATION}/${LINKTO}" "$@"
	fi
fi

# Run IDE
"${SELF_LOCATION}/AptanaStudio3" -application com.aptana.commandline.launcher.LauncherApplication "$@" > /dev/null 2>&1 &

# Detach it
disown -h %-
disown %-